@URL = https://api.themoviedb.org/3
@key = ae09140db64f8c19eae245a3b5feed8a

GET {{URL}}/movie/popular?api_key={{key}}&language=en-US&page=500&limit=10 HTTP/1.1

###

GET {{URL}}/authentication/token/new?api_key={{key}}